### ISSUE TITLE
ATTENTION AMPIE

### ISSUE THREAD

**Issue by dandare100** [entando-k8s/entando-k8s-controller-coordinator#15]
Apologies for the logged issue : 
@ampie 
I have tried the following way of getting hold of AMPIE

https://github.com/ampie/pavanecce/issues/1
https://github.com/entando-k8s/entando-k8s-controller-coordinator/pull/8
and emails

Please could someone ask him to remove an old public repository for me ?

**Comment by ampie** [comment]
Hey Jeff! I have removed the code requested and flattened the history so there should be no traces of that ever existing. Please let me know at a.barnard@entando.com if the code in question somehow still reflects in searches at all.
