### ISSUE TITLE
Operator installation in opeshift

### ISSUE THREAD

**Issue by ckvtvm-arch** [entando-k8s/entando-k8s-controller-coordinator#76]
As operator couldnt pull the image from redhat repo @ r/entando/entando-k8s-controller-coordinator, I have changed to docker hub image for the installation in openshift.

Can you please help me solve this permission issue ?
 
 forbidden: User "system:serviceaccount:gbditmft-sit:entando-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope.
                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
 
I tried the below – created a new clusterrole, role binded to the service account, but still not able to grant the required privilege to entando-operator service account !!!!
 
 
af71194@LC02CHB58MD6R entando % oc describe sa entando-operator
Name:                entando-operator
Namespace:           gbditmft-sit
Labels:              operators.coreos.com/entando-k8s-operator.gbditmft-sit=
Annotations:         <none>
Image pull secrets:  entando-operator-dockercfg-j4bf5
Mountable secrets:   entando-operator-token-6gfr6
                     entando-operator-dockercfg-j4bf5
Tokens:              entando-operator-token-6gfr6
                     entando-operator-token-bhkcg
Events:              <none>
 
af71194@LC02CHB58MD6R entando % oc describe clusterrolebinding entando-rolebinding
Name:         entando-rolebinding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  entando-role
Subjects:
  Kind            Name              Namespace
  ----            ----              ---------
  ServiceAccount  entando-operator  gbditmft-sit
 
af71194@LC02CHB58MD6R entando % oc describe clusterrole entando-role
Name:         entando-role
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources                  Non-Resource URLs  Resource Names  Verbs
  ---------                  -----------------  --------------  -----
  customresourcedefinitions  []                 []              [list]
af71194@LC02CHB58MD6R entando % kubectl auth can-i --as=entando-operator list customresourcedefinitions          
Warning: resource 'customresourcedefinitions' is not namespace scoped in group 'apiextensions.k8s.io'
no

kind: Pod
apiVersion: v1
metadata:
  generateName: entando-operator-74c859c96f-
  annotations:
    openshift.io/scc: jupyter-scc
    certified: 'false'
    olm.targetNamespaces: gbditmft-sit
    operatorframework.io/properties: >-
      {"properties":[{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoDatabaseService","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoKeycloakServer","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoClusterInfrastructure","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoPlugin","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoApp","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoAppPluginLink","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoDeBundle","version":"v1"}},{"type":"olm.gvk","value":{"group":"entando.org","kind":"EntandoCompositeApp","version":"v1"}},{"type":"olm.package","value":{"packageName":"entando-k8s-operator","version":"6.3.2-pr2"}}]}
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container
      entando-operator; cpu, memory limit for container entando-operator
    repository: ''
    support: ''
    alm-examples: >-
      [
        {"apiVersion":"entando.org/v1","kind":"EntandoDeBundle","metadata":{"name":"my-bundle","namespace":"my-namespace"},"spec":{"details":{"name":"my-bundle"}}},
        {"apiVersion":"entando.org/v1","kind":"EntandoDatabaseService","metadata":{"name":"my-entando-database-service","namespace":"my-namespace"},"spec":{"dbms":"postgresql","databaseName":"my_database","createDeployment":true}},
        {"apiVersion":"entando.org/v1","kind":"EntandoKeycloakServer","metadata":{"name":"my-keycloak","namespace":"my-namespace"},"spec":{"standardImage":"redhat-sso", "dbms":"postgresql","replicas":1,"environmentVariables":[]}},
        {"apiVersion":"entando.org/v1","kind":"EntandoClusterInfrastructure","metadata":{"name":"my-entando-cluster-infrastructure","namespace":"my-namespace"},"spec":{"replicas":1,"environmentVariables":[]}},
        {"apiVersion":"entando.org/v1","kind":"EntandoPlugin","metadata":{"name":"my-entando-plugin","namespace":"my-namespace"},"spec": {"dbms": "postgresql","healthCheckPath": "/management/health","image":
      "entando/entando-avatar-plugin:6.0.5","ingressHostName":
      "my-plugin.apps-crc.testing","ingressPath": "/avatarPlugin","replicas":
      1,"roles": [{"code": "admin","name": "user"},{"code": "user","name":
      "user"}],"securityLevel": "strict"}},
        {"apiVersion":"entando.org/v1","kind":"EntandoApp","metadata":{"name":"my-app","namespace":"my-namespace"},"spec":{"dbms":"postgresql","environmentVariables":[],"ingressHostName":"my-app.apps-crc.testing","replicas":1,"standardServerImage":"eap"}},
        {"apiVersion":"entando.org/v1","kind":"EntandoAppPluginLink","metadata":{"name":"my-link","namespace":"my-namespace"},"spec":{"entandoAppName":"my-app","entandoPluginName":"my-plugin"}},
        {"apiVersion":"entando.org/v1","kind":"EntandoCompositeApp","metadata":{"name":"my-entando-composite-app","namespace":"my-namespace"},"spec":{"dbmsOverride":"postgresql","ingressHostNameOverride":"entando.apps-crc.testing","components":[{"kind":"EntandoDatabaseService","metadata":{"name":"inline-entando-database-service"},"spec":{"createDeployment":true}},{"kind":"EntandoKeycloakServer","metadata":{"name":"inline-keycloak"},"spec":{"standardImage":"redhat-sso"}},{"kind":"EntandoClusterInfrastructure","metadata":{"name":"inline-entando-cluster-infrastructure"},"spec":{}},{"kind":"EntandoApp","metadata":{"name":"inline-app"},"spec":{"standardServerImage":"eap"}},{"kind":"EntandoPlugin","metadata":{"name":"inline-plugin"},"spec":{"healthCheckPath":"/management/health","image":"entando/entando-avatar-plugin:6.0.5","ingressPath":"/avatarPlugin","roles":[{"code":"admin","name":"admin"},{"code":"user","name":"user"}]}},{"kind":"EntandoAppPluginLink","metadata":{"name":"inline-link"},"spec":{"entandoAppName":"inline-app","entandoPluginName":"inline-plugin"}}]}}
      ]
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.129.15.120"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.129.15.120"
          ],
          "default": true,
          "dns": {}
      }]
    capabilities: Basic Install
    olm.operatorNamespace: gbditmft-sit
    containerImage: >-
      registry.hub.docker.com/entando/entando-k8s-controller-coordinator:0.0.0-SNAPSHOT-PR-75-37
    createdAt: ''
    categories: Developer Tools
    description: >-
      Processes EntandoKeycloakServer, EntandoApp and EntandoPlugin custom
      resources and deploys the relevant containers in the Kubernetes cluster.
    olm.operatorGroup: gbditmft-sit-gv957
  selfLink: /api/v1/namespaces/gbditmft-sit/pods/entando-operator-74c859c96f-5rrmr
  resourceVersion: '18821670745'
  name: entando-operator-74c859c96f-5rrmr
  uid: cbab443f-7629-467a-8f91-a32eea66f7b7
  creationTimestamp: '2021-06-30T00:24:23Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-06-30T00:24:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:olm.operatorNamespace': {}
            'f:createdAt': {}
            'f:alm-examples': {}
            'f:description': {}
            'f:olm.operatorGroup': {}
            'f:capabilities': {}
            .: {}
            'f:categories': {}
            'f:certified': {}
            'f:operatorframework.io/properties': {}
            'f:support': {}
            'f:olm.targetNamespaces': {}
            'f:repository': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:k8s-app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"97091c5d-25b3-4036-854d-5e96e621bca2"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"entando-operator"}':
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:livenessProbe':
                .: {}
                'f:exec':
                  .: {}
                  'f:command': {}
                'f:failureThreshold': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:env':
                'k:{"name":"ENTANDO_K8S_OPERATOR_SECURITY_MODE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_RHEL8_POSTGRESQL_12"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_COMPOSITE_APP_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_APP_PLUGIN_LINK_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_DBJOB"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_COMPLIANCE_MODE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_GC_CONTROLLER_PODS"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_POD_READINESS_TIMEOUT_SECONDS"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_COMPONENT_MANAGER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"POD_NAME"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:fieldRef':
                      .: {}
                      'f:apiVersion': {}
                      'f:fieldPath': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_APP_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_PLUGIN_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                .: {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_DATABASE_SERVICE_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_KEYCLOAK_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_VERSION_TO_REPLACE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_SERVICEACCOUNT"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:fieldRef':
                      .: {}
                      'f:apiVersion': {}
                      'f:fieldPath': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_DE_APP_EAP"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_REDHAT_SSO"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_DEPLOYMENT_TYPE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_NAMESPACES_TO_OBSERVE"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:fieldRef':
                      .: {}
                      'f:apiVersion': {}
                      'f:fieldPath': {}
                'k:{"name":"RELATED_IMAGE_RHEL8_MYSQL_80"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_VERSION"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_K8S_OPERATOR_FORCE_DB_PASSWORD_RESET"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_APP_BUILDER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_CLUSTER_INFRASTRUCTURE_CONTROLLER"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"OPERATOR_NAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"RELATED_IMAGE_ENTANDO_K8S_SERVICE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:readinessProbe':
                .: {}
                'f:exec':
                  .: {}
                  'f:command': {}
                'f:failureThreshold': {}
                'f:periodSeconds': {}
                'f:successThreshold': {}
                'f:timeoutSeconds': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:serviceAccount': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:nodeSelector':
            .: {}
            'f:beta.kubernetes.io/os': {}
          'f:terminationGracePeriodSeconds': {}
          'f:imagePullSecrets':
            .: {}
            'k:{"name":"entando-pull-secret"}':
              .: {}
              'f:name': {}
          'f:serviceAccountName': {}
          'f:enableServiceLinks': {}
          'f:securityContext': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2021-06-30T00:24:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2021-06-30T00:29:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:containerImage': {}
        'f:spec':
          'f:containers':
            'k:{"name":"entando-operator"}':
              'f:image': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-06-30T17:23:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.129.15.120"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
  namespace: gbditmft-sit
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: entando-operator-74c859c96f
      uid: 97091c5d-25b3-4036-854d-5e96e621bca2
      controller: true
      blockOwnerDeletion: true
  labels:
    k8s-app: entando-operator
    pod-template-hash: 74c859c96f
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Always
  serviceAccountName: entando-operator
  imagePullSecrets:
    - name: entando-pull-secret
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: va33dlvocp030.ent-ocp4-np1-har.antmdc.internal.das
  securityContext:
    seLinuxOptions:
      level: 's0:c63,c47'
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 500Mi
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/EntandoControllerCoordinator.ready
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1
      terminationMessagePath: /dev/termination-log
      name: entando-operator
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/EntandoControllerCoordinator.ready
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 1
      env:
        - name: ENTANDO_NAMESPACES_TO_OBSERVE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ENTANDO_POD_READINESS_TIMEOUT_SECONDS
          value: '1000'
        - name: ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS
          value: '1000'
        - name: ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT
          value: 'true'
        - name: ENTANDO_K8S_OPERATOR_VERSION
          value: 6.3.2-pr2
        - name: ENTANDO_K8S_OPERATOR_VERSION_TO_REPLACE
          value: 0.3.56
        - name: ENTANDO_K8S_OPERATOR_DEPLOYMENT_TYPE
          value: olm
        - name: OPERATOR_NAME
          value: entando-operator
        - name: ENTANDO_K8S_OPERATOR_GC_CONTROLLER_PODS
          value: 'true'
        - name: ENTANDO_K8S_OPERATOR_SECURITY_MODE
          value: lenient
        - name: ENTANDO_K8S_OPERATOR_COMPLIANCE_MODE
          value: redhat
        - name: ENTANDO_K8S_OPERATOR_FORCE_DB_PASSWORD_RESET
          value: 'true'
        - name: ENTANDO_K8S_OPERATOR_SERVICEACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: RELATED_IMAGE_RHEL8_MYSQL_80
          value: >-
            registry.redhat.io/rhel8/mysql-80@sha256:570bce7dc649ac7ac85e7ecb196aabc281c77a94590aa7df7d9746869ce757ea
        - name: RELATED_IMAGE_RHEL8_POSTGRESQL_12
          value: >-
            registry.redhat.io/rhel8/postgresql-12@sha256:f4e5c728b644bf1888ec8086424852ed74b5596a511be29e636fb10218fc9b6f
        - name: RELATED_IMAGE_APP_BUILDER
          value: >-
            docker.io/entando/app-builder@sha256:1ca90c09302b9cadf8950278d92ad4d7f3a14f02dea8704320794aa77ada8631
        - name: RELATED_IMAGE_ENTANDO_COMPONENT_MANAGER
          value: >-
            docker.io/entando/entando-component-manager@sha256:668191fc86b090452baaba18ec7bbc3d07df5a99750e0c5b98759599d565cfbe
        - name: RELATED_IMAGE_ENTANDO_DE_APP_EAP
          value: >-
            docker.io/entando/entando-de-app-eap@sha256:1f0e35d7f7ee8123721cf8e80ac96ac2f594f21a2b68cf9e720917d090c8095e
        - name: RELATED_IMAGE_ENTANDO_K8S_APP_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-app-controller@sha256:c68d3b129fc625f5d1ee10ed2a107e28c145049d4b513dcdb2c736555025e339
        - name: RELATED_IMAGE_ENTANDO_K8S_APP_PLUGIN_LINK_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-app-plugin-link-controller@sha256:aa7ba0861705213434e610530c5bf5da1bdb33f1834d3c346174f5a28145c0bd
        - name: RELATED_IMAGE_ENTANDO_K8S_CLUSTER_INFRASTRUCTURE_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-cluster-infrastructure-controller@sha256:86dbea6696349d7b2393e12bacef4d1acec2dd3f8551e397fa26c92706a18dd3
        - name: RELATED_IMAGE_ENTANDO_K8S_COMPOSITE_APP_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-composite-app-controller@sha256:4bc6797bb41b3e407b64530c3cff7a78f3fc2c22863caad9c606ccd650310b61
        - name: RELATED_IMAGE_ENTANDO_K8S_DATABASE_SERVICE_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-database-service-controller@sha256:58ca4ad2fca83a715aba9b68609f9056f633d556eb9845b3aff5c05769369539
        - name: RELATED_IMAGE_ENTANDO_K8S_DBJOB
          value: >-
            docker.io/entando/entando-k8s-dbjob@sha256:8ae47dbf93201965106663299f06daad544982fa244d4a0f365a1b717727e5ed
        - name: RELATED_IMAGE_ENTANDO_K8S_KEYCLOAK_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-keycloak-controller@sha256:f1ed42001260802353197433cea7df4c2d0e5fd9bcd926bb5ae7c654dfad2ffe
        - name: RELATED_IMAGE_ENTANDO_K8S_PLUGIN_CONTROLLER
          value: >-
            docker.io/entando/entando-k8s-plugin-controller@sha256:a20c753dda86e0f54f210e446b404733045ba426fc7186dc3936daed8224fbcb
        - name: RELATED_IMAGE_ENTANDO_K8S_SERVICE
          value: >-
            docker.io/entando/entando-k8s-service@sha256:775391f0005e64764288bfe007d9ea576f13618c02ea400d030a7502cfb551bd
        - name: RELATED_IMAGE_ENTANDO_REDHAT_SSO
          value: >-
            docker.io/entando/entando-redhat-sso@sha256:3692adb3694b3bf278bed7a678c9d0eaa0aba8e3e3ed4117ca04156525bcac72
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent
      startupProbe:
        exec:
          command:
            - cat
            - /tmp/EntandoControllerCoordinator.ready
        timeoutSeconds: 1
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 50
      volumeMounts:
        - name: entando-operator-token-6gfr6
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        registry.hub.docker.com/entando/entando-k8s-controller-coordinator:0.0.0-SNAPSHOT-PR-75-37
  serviceAccount: entando-operator
  volumes:
    - name: entando-operator-token-6gfr6
      secret:
        secretName: entando-operator-token-6gfr6
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-06-30T00:24:23Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-06-30T00:24:23Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [entando-operator]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-06-30T00:24:23Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [entando-operator]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-06-30T00:24:23Z'
  hostIP: 30.118.44.32
  podIP: 10.129.15.120
  podIPs:
    - ip: 10.129.15.120
  startTime: '2021-06-30T00:24:23Z'
  containerStatuses:
    - restartCount: 202
      started: false
      ready: false
      name: entando-operator
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=entando-operator
            pod=entando-operator-74c859c96f-5rrmr_gbditmft-sit(cbab443f-7629-467a-8f91-a32eea66f7b7)
      imageID: >-
        registry.hub.docker.com/entando/entando-k8s-controller-coordinator@sha256:68fa47521cf9ecce0b67e495ea5a6ab44aec7c2d38a26ccd3c61a4aa639fadb0
      image: >-
        registry.hub.docker.com/entando/entando-k8s-controller-coordinator:0.0.0-SNAPSHOT-PR-75-37
      lastState:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2021-06-30T17:23:32Z'
          finishedAt: '2021-06-30T17:23:35Z'
          containerID: >-
            cri-o://7eadb57beb0add5f786431a846a568757e2c238dcc7a2d14618ea0019f2936cc
      containerID: 'cri-o://7eadb57beb0add5f786431a846a568757e2c238dcc7a2d14618ea0019f2936cc'
  qosClass: Burstable

---------------------------------ERROR LOG---------------------------------------
Log stream ended.

Container
C
entando-operator
Show in Kibana
|
Raw
|
Download
|
39 lines
exec java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-30 17:38:46,874 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?labelSelector=entando.org%2Fcrd-of-interest. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:gbditmft-sit:entando-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:520)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:487)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:161)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:664)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:86)
	at org.entando.kubernetes.controller.coordinator.DefaultSimpleKubernetesClient.loadCustomResourceDefinitionsOfInterest(DefaultSimpleKubernetesClient.java:198)
	at org.entando.kubernetes.controller.coordinator.EntandoControllerCoordinator.onStartup(EntandoControllerCoordinator.java:71)
	at org.entando.kubernetes.controller.coordinator.EntandoControllerCoordinator_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.notify(EntandoControllerCoordinator_Observer_onStartup_8d7b338c7415a5b0bcaaf3b82fd300311baae948.zig:147)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:369)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)

**Comment by nshaw** [comment]
Just noting we also have a conversation about this in the forum here - https://forum.entando.org/t/entando-operator-installation-in-openshift/195/4

**Comment by ckvtvm-arch** [comment]
I was installing the operator from operatorhub. My OCP version is 4.7 hosted in RedHat openshift container platform.

I havent issued any command, the installation fails with the absence of image and I switched to docker image for entando-k8s-controller-coordinator

I am running into the permission issue post changing the image

forbidden: User “system:serviceaccount:gbditmft-sit:entando-operator” cannot list resource “customresourcedefinitions” in API group “” at the cluster scope.

**Comment by ckvtvm-arch** [comment]
I am not able to post messages in forum due to some reason

**Comment by ckvtvm-arch** [comment]
this is resolved by @nshaw
